### ISSUE TITLE
Request: Below normal priority

### ISSUE THREAD

**Issue by God-damnit-all** [1480c1/media-autobuild_suite#5] opened 2020-04-29 20:14 UTC
Posting this here since you would handle it anyway and I really don't appreciate wiiaboo's attitude.

It would be convenient to have all processes launch with 'Below Normal' priority. This could be an option but honestly, if nothing else is running it won't matter, so this seems like a no-brainer for all circumstances. It'd make it so I could compile any time I wanted without having to worry about it soft-locking things from time to time.

Windows has a command that allows for this (https://ss64.com/nt/start.html), but I don't think it's recursive, and I don't know if this is possible to do in mintty considering it's a Linuxy environment.

**Comment by 1480c1** [comment] 2020-04-29 20:28
Althugh we do use `start`, I will need to see how it impacts subprocesses

**Comment by God-damnit-all** [comment] 2020-04-29 20:45
As an aside, is this STILL an issue?
https://github.com/m-ab-s/media-autobuild_suite/blob/master/build/media-suite_compile.sh#L1869

**Comment by 1480c1** [comment] 2020-04-29 20:46
Yep https://github.com/OpenVisualCloud/SVT-AV1/issues/567

**Comment by God-damnit-all** [comment] 2020-04-29 20:48
I'm afraid changing the link like that doesn't work to remove the mention, but feel free to close and delete this issue.

**Comment by 1480c1** [comment] 2020-04-29 20:49
Ehh, it's fine

**Comment by 1480c1** [comment] 2020-05-02 03:20
Seems the low prio thing works with `start`, now just need to make sure it works as intended

**Comment by God-damnit-all** [comment] 2020-05-11 15:03
Is there a branch/patch that you'd like me to test?

**Comment by 1480c1** [comment] 2020-05-11 15:08
Not yet, although I implemented a local branch, I haven't made sure it's correct since I was also working on splitting the bat file into smaller files etc. I can try to put that on pause and see if this can be added

**Comment by God-damnit-all** [comment] 2020-05-11 15:25
Honestly the batch system is so archaic that splitting functions off into separate files and calling/importing them might not be a good idea, it seems like a recipe for unexpected bugs (especially on non-English locales).

The amount of weird shit that will happen on Russian or Asian language command lines is obscene and nonsensical, so I always advocate on keeping the batch portions as simple as possible.

Have you thought about switching to PowerShell 5.1? There's a really clever way to embed a powershell script into a batch script without any bugs or need to have a user change their executionpolicy setting.

**Comment by God-damnit-all** [comment] 2020-05-11 15:30
Here's the most basic way of getting it done, switching to all Unicode inputs immediately in the process:
```
<# ::
@echo off & chcp 65001 >NUL
powershell -NoP -NoL -c "iex (${%~f0} | Out-String)" 
exit /b %errorlevel%
:: #>

# (This is where the PowerShell portion begins.)

$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
```
Add `pushd %~dp0` somewhere in the batch section (and popd just before exit) if you want it to be launchable as admin.

Also you can pipe commands with complicated inputs and lots of special characters to cmd like this:
```pwsh
@"
long command here
"@ | cmd
# Alternatively, pipe to $env:COMSPEC
# For no output, add >$NULL at the end.
```

**Comment by 1480c1** [comment] 2020-05-11 15:36
Rather than splitting the batch file into multiple bat files, I'm taking the Powershell route. You can find what might be considered my current progress for that in the powershell2 branch

**Comment by 1480c1** [comment] 2020-05-11 15:37
I'm also doing that to try to split off vlc building into a separate project since it's honestly a bit of a pain at the current moment because of dependency stuff

**Comment by God-damnit-all** [comment] 2020-05-11 15:39
Alright, hopefully you find the hybrid script up there useful, I like it because it completely bypasses ExecutionPolicy and gives an easy and consistent launch point.

**Comment by God-damnit-all** [comment] 2020-05-14 17:02
In regards to the PowerShell stuff again, there is a project that, while it doesn't have interactive prompts like media-autobuild_suite does, does perform a very long sequence of events in PowerShell 5.1 and follows all of the best practices.

https://github.com/DrEmpiricism/Optimize-Offline

**Comment by 1480c1** [comment] 2020-05-14 17:03
I'm not so sure how well using a similar structure to that project would work considering that project is an actual PowerShell package rather than a project that uses powershell

**Comment by God-damnit-all** [comment] 2020-05-15 02:21
Oh, I wasn't suggesting a similar overall structure so much as I was suggesting it as a good reference on the best way to do very specific things in PowerShell 5.1.

PowerShell 5.1 has a lot of arcane idiosyncrasies much like batch (although not nearly as bad).

**Comment by God-damnit-all** [comment] 2020-05-18 17:17
I noticed you have PRs on the SVT-AV1 repo open. Any chance the changes will finally fix the inability to compile it into ffmpeg with libaom and libopencore-amrwb?

**Comment by 1480c1** [comment] 2020-05-18 17:30
That's one of the things I am working one, yes

**Comment by 1480c1** [comment] 2020-05-23 05:24
Currently in the prio branch on this repo, testing atm

Running mabs with `/low` hardcoded worked and msys2 and the spawned process all launched with low priority and running with noMintty=1 worked and bash launched with low priority

**Comment by 1480c1** [comment] 2020-05-23 16:28
1669

**Comment by 1480c1** [comment] 2020-05-23 21:30
merged

**Closed as completed by 1480c1** 2020-05-23 21:30 UTC

**Comment by God-damnit-all** [comment] 2020-05-23 23:35
Thanks!
